# neo4jのコンテナ
# docker-compose up -d で起動
# localhost:7474にアクセス
version: '3'
services:
    neo4j:
        image: neo4j
        ports:
            - 7474:7474
            - 7687:7687
        volumes:
            - ./neo4j/data:/data
            - ./neo4j/logs:/logs
            - ./neo4j/conf:/conf
